services:
  kronic:
    image: ghcr.io/mshade/kronic
    build:
      context: .
      target: dev
    environment:
      KRONIC_ALLOW_NAMESPACES: "test"
      KRONIC_ADMIN_PASSWORD: "test2"
      KUBECONFIG: "/home/kronic/.kube/config"
    volumes:
      - .:/app
      - $HOME/.kube/kronic-localdev-container.yaml:/home/kronic/.kube/config
    ports:
      - 5000:5000
    networks:
      - k3d-kronic-localdev

networks:
  k3d-kronic-localdev:
    external: true
