{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kronic.fullname" . }}
  labels:
    {{- include "kronic.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kronic.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      {{- if .Values.networkPolicy.namespaceSelector }}
      - namespaceSelector:
          {{- toYaml .Values.networkPolicy.namespaceSelector | nindent 8 }}
      {{- else }}
      - namespaceSelector: {}
      {{- end }}
      {{- if .Values.networkPolicy.podSelector }}
      - podSelector:
          {{- toYaml .Values.networkPolicy.podSelector | nindent 8 }}
      {{- end }}
      ports:
        - protocol: TCP
          port: 8000
    {{- if .Values.networkPolicy.additionalIngress }}
    {{- toYaml .Values.networkPolicy.additionalIngress | nindent 4 }}
    {{- end }}
{{- end }}