{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kronic.fullname" . }}
  labels:
    {{- include "kronic.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kronic.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if has "Ingress" .Values.networkPolicy.policyTypes }}
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
      {{- if .Values.networkPolicy.ingress.from }}
      from:
        {{- toYaml .Values.networkPolicy.ingress.from | nindent 8 }}
      {{- end }}
  {{- end }}
  {{- if has "Egress" .Values.networkPolicy.policyTypes }}
  egress:
    {{- if .Values.networkPolicy.egress.to }}
    {{- range .Values.networkPolicy.egress.to }}
    - to:
        {{- toYaml . | nindent 8 }}
      {{- if $.Values.networkPolicy.egress.ports }}
      ports:
        {{- toYaml $.Values.networkPolicy.egress.ports | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- else }}
    # Default egress rules when none specified
    - {} # Allow all egress
    {{- end }}
  {{- end }}
{{- end }}