{{- if and .Values.database.enabled (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kronic.fullname" . }}-postgres
  labels:
    {{- include "kronic.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  password: {{ .Values.database.password | default (randAlphaNum 16) | b64enc | quote }}
{{- end }}