name: Chart Testing and Release

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'
      - '.github/workflows/chart-testing.yaml'

jobs:
  lint-test-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: |
          ct lint --charts chart/kronic --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0

      - name: Run chart-testing (install)
        run: |
          ct install --charts chart/kronic \
            --helm-extra-args '--timeout 60s' \
            --helm-extra-set-args '--set=image.tag=latest' \
            --target-branch ${{ github.event.repository.default_branch }}

  release-chart:
    if: github.ref == 'refs/heads/main'
    needs: lint-test-chart
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.12.3'
      - name: Generate Chart Readme
        run: ./.github/gen-chart-readme.sh

      - name: Create gh-pages branch if it doesn't exist
        run: |
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            echo "gh-pages branch does not exist, creating it..."
            git checkout --orphan gh-pages
            git reset --hard
            mkdir -p .cr-index
            echo -e "apiVersion: v1\nentries: {}\ngenerated: \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"" > .cr-index/index.yaml
            git add .cr-index/index.yaml
            git commit -m "Initialize gh-pages branch for Helm chart repository"
            git push origin gh-pages
            git checkout -
          else
            echo "gh-pages branch already exists"
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ./chart
        env:
          CR_SKIP_EXISTING: "true"
          CR_RELEASE_NAME_TEMPLATE: "{{ .Name }}-chart-{{ .Version }}"
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
